# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadai < Formula
  desc "CLI tool that standardizes AI coding agent environments across a team"
  homepage "https://github.com/PedroMosquera/squadai"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PedroMosquera/squadai/releases/download/v0.2.1/squadai_0.2.1_darwin_amd64.tar.gz"
      sha256 "c3a28f7d206c5ae491d745638e84ca05cb664e2a1e2501375dca82be6b304b96"

      define_method(:install) do
        bin.install "squadai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PedroMosquera/squadai/releases/download/v0.2.1/squadai_0.2.1_darwin_arm64.tar.gz"
      sha256 "100ae6d10f410381ba57c2d9b017e37a7e437efaa7226288d825bebebd864b89"

      define_method(:install) do
        bin.install "squadai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PedroMosquera/squadai/releases/download/v0.2.1/squadai_0.2.1_linux_amd64.tar.gz"
      sha256 "f1b92ba144b3cff90b87c61a29de2c716513ac1226df16f31d0a7653ed46afd2"
      define_method(:install) do
        bin.install "squadai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PedroMosquera/squadai/releases/download/v0.2.1/squadai_0.2.1_linux_arm64.tar.gz"
      sha256 "cc626498cfb52b7b84b7210a25635e999b79ab8ae5f0c9397638f95ed7fc2879"
      define_method(:install) do
        bin.install "squadai"
      end
    end
  end

  test do
    system "#{bin}/squadai", "version"
  end
end
