# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadai < Formula
  desc "CLI tool that standardizes AI coding agent environments across a team"
  homepage "https://github.com/PedroMosquera/squadai"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PedroMosquera/squadai/releases/download/v0.2.0/squadai_0.2.0_darwin_amd64.tar.gz"
      sha256 "86e93d287a9a98f5e183be6277dbe1bba37e530773377b35e746a5c523a9505c"

      define_method(:install) do
        bin.install "squadai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PedroMosquera/squadai/releases/download/v0.2.0/squadai_0.2.0_darwin_arm64.tar.gz"
      sha256 "1564f2753849f23047eee151f64e64b1cff0ff8bc376f87b4b7f1f4145b58c52"

      define_method(:install) do
        bin.install "squadai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PedroMosquera/squadai/releases/download/v0.2.0/squadai_0.2.0_linux_amd64.tar.gz"
      sha256 "fd69df5c8b78f97a1c18576c9158d36d853ffbd8f395bbcd196011427421d977"
      define_method(:install) do
        bin.install "squadai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PedroMosquera/squadai/releases/download/v0.2.0/squadai_0.2.0_linux_arm64.tar.gz"
      sha256 "17e44ffbb6d7ead60a957090a205b47b35ea2524290309992fe4da14ebbabb9f"
      define_method(:install) do
        bin.install "squadai"
      end
    end
  end

  test do
    system "#{bin}/squadai", "version"
  end
end
